### ISSUE TITLE
Rewrite without AI

### ISSUE THREAD

**Issue by Julian-Mostbauer** [Integr-0/Trajectory#2]
![grafik](https://github.com/Integr-0/Trajectory/assets/146772868/7fcb9366-d69e-4d92-8140-f683aa3a2760)

**Comment by Integr-0** [comment]
@Julian-Mostbauer 
@Julian-Mostbauer 
@Julian-Mostbauer 
@Julian-Mostbauer 
@Julian-Mostbauer 
@Julian-Mostbauer 
@Julian-Mostbauer 
@Julian-Mostbauer 
@Julian-Mostbauer 
@Julian-Mostbauer 
@Julian-Mostbauer 
@Julian-Mostbauer

**Comment by Julian-Mostbauer** [comment]
@Integr-0

**Comment by Julian-Mostbauer** [comment]
[Uploading pointPlotter.pdf…]()

**Comment by Julian-Mostbauer** [comment]
![nature-forest-trees-41102](https://github.com/Integr-0/Trajectory/assets/146772868/9cd695e0-75ce-4956-b173-7fcc1a9a0d04)
